### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'file' for task.output

### ISSUE THREAD

**Issue by thomzi12** [steamship-core/steamship-langchain#45]
https://github.com/steamship-core/steamship-langchain/blame/ca61185ed6914b6695984f1723e2dcecbafc280e/src/steamship_langchain/llms/openai.py#L185

Hi! I forked "Question Answering with Sources using LangChain on Steamship" on Replit. I created a Steamship API key and saved it as a secret. But when I tried running the app I hit this error. It seems to originate at this line mentioned above. 

Is this bug, or more likely, am I making a dumb mistake somewhere?

My goal: get a langchain app up and running. Then, modify prompting/fine-tuning etc for my own goals. 

![image](https://github.com/steamship-core/steamship-langchain/assets/8431251/331a48ab-994e-4c74-bea7-97c9bcf8df17)

**Comment by thomzi12** [comment]
I'm also hitting this error on a fork of "Simple LangChain Prompting on Steamship": 

```
Name: Zachary
Traceback (most recent call last):
  File "api.py", line 59, in <module>
    print(colored(f'{api.greet(user=name).strip()}\n', "green"))
  File "/home/runner/Simple-LangChain-Prompting-on-Steamship/venv/lib/python3.8/site-packages/steamship/invocable/invocable.py", line 61, in wrap
    return function(self, *args, **kwargs)
  File "api.py", line 34, in greet
    return llm(prompt.format(user=user))
  File "/home/runner/Simple-LangChain-Prompting-on-Steamship/venv/lib/python3.8/site-packages/langchain/llms/base.py", line 145, in __call__
    return self.generate([prompt], stop=stop).generations[0][0].text
  File "/home/runner/Simple-LangChain-Prompting-on-Steamship/venv/lib/python3.8/site-packages/langchain/llms/base.py", line 86, in generate
    raise e
  File "/home/runner/Simple-LangChain-Prompting-on-Steamship/venv/lib/python3.8/site-packages/langchain/llms/base.py", line 83, in generate
    output = self._generate(prompts, stop=stop)
  File "/home/runner/Simple-LangChain-Prompting-on-Steamship/venv/lib/python3.8/site-packages/steamship_langchain/llms/openai.py", line 71, in _generate
    sub_generations = self._batch(prompts=_prompts, stop=stop)
  File "/home/runner/Simple-LangChain-Prompting-on-Steamship/venv/lib/python3.8/site-packages/steamship_langchain/llms/openai.py", line 113, in _batch
    generation_file = task.output.file
AttributeError: 'NoneType' object has no attribute 'file'
```

**Comment by douglas-reid** [comment]
@thomzi12 Unfortunately, I'm not able to duplicate this issue. What happens if you try running it again?

If the `task` fails, I suppose we could see this issue. PR sent to help tease it out.
